//
// Created by Michael on 2018/12/18.
//

#ifndef LOCKFREEC_PSEUDOIO_H
#define LOCKFREEC_PSEUDOIO_H

#define DESCRIPTOR_POOL_SIZE 4096
#define WORD_DESCRIPTOR_SIZE 10

#endif //LOCKFREEC_PSEUDOIO_H
